# Rust toolchain configuration for Amari
#
# The project uses stable Rust by default for production builds
# Nightly is required only for formal verification features with Creusot

[toolchain]
# Use nightly for formal verification with Creusot contracts
channel = "nightly"

# Components we need
components = ["rustfmt", "clippy"]

# Note: Nightly is required for formal verification features with Creusot
# For stable-only development without formal verification:
#   cargo +stable build