[package]
name = "amari-automata"
version = "0.1.0"
edition = "2021"
description = "Cellular automata, inverse design, and self-assembly using geometric algebra"
authors = ["Elliott Hall <elliott@example.com>"]
license = "MIT OR Apache-2.0"

[dependencies]
amari-core = { path = "../amari-core", version = "0.1" }
amari-tropical = { path = "../amari-tropical", version = "0.1" }
amari-dual = { path = "../amari-dual", version = "0.1" }
num-traits = "0.2"
serde = { version = "1.0", features = ["derive"], optional = true }

[features]
default = []
serde-support = ["serde"]

[dev-dependencies]
approx = "0.5"
criterion = "0.5"

